### ISSUE TITLE
Join es-shims?

### ISSUE THREAD

**Issue by ljharb** [es-shims/Object.getPrototypeOf#1]
Hi there!

Would you be interested in contributing your git repo to the es-shims orgs? https://github.com/es-shims I've already spoken to @mightyiam, and they're willing :-)

I'd love to take over maintenance of this package and update it to be more robust, and to help complete the larger collection of polyfills/shims we already have.

If you're interested, please let me know which username I should invite to the es-shims github org :-)

**Comment by mightyiam** [comment]
I'm 👍 with that, if that matters.

**Comment by kylegibson-rldatix** [comment]
Yup, this makes sense. Let's do it. What do I need to do?

**Comment by ljharb** [comment]
Yay! @kylegibson, I’ve just invited you to the es-shims org; once accepted you can transfer the repo in, and @mightyiam can `npm owner add ljharb`, and I’ll proceed from there :-)

**Comment by mightyiam** [comment]
Done.

**Comment by ljharb** [comment]
@kylegibson please let me know if you need any help with next steps :-D

**Comment by ljharb** [comment]
Thanks! I'll update the package to be maximally robust soon :-) much obliged!
